apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: flux-system
data:
  NODE_IP: "192.168.100.98"
  NFS_SERVER: "192.168.100.98"
  METALLB_IP_RANGE: "192.168.100.200-192.168.100.250"
  NETWORK_INTERFACE: "wlp2s0"
