# This storage class is kept for backwards compatibility
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
# Adding new storage class that uses the dynamic provisioner
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client-dynamic
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
parameters:
  archiveOnDelete: "false"
---
# The following PVs are kept for existing deployments
# For new deployments, use the dynamic provisioner with PVCs only
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server-pv
  labels:
    app: prometheus
    component: server
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 192.168.100.98
    path: /data/prometheus
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  labels:
    app: grafana
    component: server
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 192.168.100.98
    path: /data/grafana
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-pv-0
  labels:
    app: alertmanager
    component: server
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 192.168.100.98
    path: /data/alertmanager-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-pv-1
  labels:
    app: alertmanager
    component: server
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 192.168.100.98
    path: /data/alertmanager-1