network:
  version: 2
  ethernets:
    ens3:
      dhcp4: no
      addresses:
        - 10.234.181.100/24  # Assign a static IP
      routes:
        - to: default
          via: 10.234.181.1  # Your network's gateway
      nameservers:
        addresses:
          - 1.1.1.1  # Cloudflare DNS
          - 8.8.8.8  # Google DNS

