---
# ServiceMonitor for Flux Source Controller
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: source-controller
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: source-controller
spec:
  selector:
    matchLabels:
      app: source-controller
  endpoints:
    - port: http-prom
      interval: 30s
      path: /metrics
---
# ServiceMonitor for Flux Kustomize Controller
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kustomize-controller
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: kustomize-controller
spec:
  selector:
    matchLabels:
      app: kustomize-controller
  endpoints:
    - port: http-prom
      interval: 30s
      path: /metrics
---
# ServiceMonitor for Flux Helm Controller
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: helm-controller
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: helm-controller
spec:
  selector:
    matchLabels:
      app: helm-controller
  endpoints:
    - port: http-prom
      interval: 30s
      path: /metrics
---
# ServiceMonitor for Flux Notification Controller
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notification-controller
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: notification-controller
spec:
  selector:
    matchLabels:
      app: notification-controller
  endpoints:
    - port: http-prom
      interval: 30s
      path: /metrics
