apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: tempo
      version: 1.24.4
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    tempo:
      repository: grafana/tempo
      tag: 2.9.0
      retention: 168h
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
        jaeger:
          protocols:
            grpc:
              endpoint: 0.0.0.0:14250
            thrift_http:
              endpoint: 0.0.0.0:14268
        zipkin:
          endpoint: 0.0.0.0:9411
      storage:
        trace:
          backend: local
          local:
            path: /var/tempo/traces
    tempoQuery:
      enabled: false
    securityContext:
      fsGroup: 10001
      runAsGroup: 10001
      runAsUser: 10001
    persistence:
      enabled: true
      storageClassName: nfs-client
      size: 10Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
